services:
  minecraft-server:
    image: jtreed/mcserver:latest
    volumes:
      - minecraft-world:/app/storage
    ports: 
      - 25565:25565
      - 25575:25575
    stop_grace_period: 1m

volumes:
  minecraft-world:
